const styles = {
  page: {
    position: 'relative',
    minHeight: '100vh',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px 24px',
    background: 'linear-gradient(135deg, #0f0f1a 0%, #1a1a2e 40%, #16213e 100%)',
    overflow: 'hidden',
    fontFamily: "'Inter', system-ui, sans-serif",
  },
  // Background orbs
  orb1: {
    position: 'absolute',
    top: '10%',
    right: '15%',
    width: '300px',
    height: '300px',
    borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(99, 102, 241, 0.15) 0%, transparent 70%)',
    filter: 'blur(40px)',
    animation: 'float 8s ease-in-out infinite',
    pointerEvents: 'none',
  },
  orb2: {
    position: 'absolute',
    bottom: '15%',
    left: '10%',
    width: '250px',
    height: '250px',
    borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(6, 214, 160, 0.12) 0%, transparent 70%)',
    filter: 'blur(40px)',
    animation: 'float2 10s ease-in-out infinite',
    pointerEvents: 'none',
  },
  orb3: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '400px',
    height: '400px',
    borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(139, 92, 246, 0.08) 0%, transparent 70%)',
    filter: 'blur(60px)',
    animation: 'pulse-glow 6s ease-in-out infinite',
    pointerEvents: 'none',
  },
  gridOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundImage: `
      linear-gradient(rgba(255,255,255,0.02) 1px, transparent 1px),
      linear-gradient(90deg, rgba(255,255,255,0.02) 1px, transparent 1px)
    `,
    backgroundSize: '60px 60px',
    pointerEvents: 'none',
  },
  // Brand
  brand: {
    position: 'relative',
    zIndex: 10,
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '24px',
  },
  logoMark: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoText: {
    fontSize: '20px',
    fontWeight: 800,
    color: 'rgba(255, 255, 255, 0.95)',
    letterSpacing: '-0.02em',
  },
  // Heading
  heading: {
    position: 'relative',
    zIndex: 10,
    fontSize: 'clamp(1.75rem, 4vw, 2.5rem)',
    fontWeight: 800,
    color: 'rgba(255, 255, 255, 0.95)',
    textAlign: 'center',
    marginBottom: '8px',
    letterSpacing: '-0.03em',
  },
  subheading: {
    position: 'relative',
    zIndex: 10,
    fontSize: '15px',
    color: 'rgba(255, 255, 255, 0.4)',
    textAlign: 'center',
    marginBottom: '28px',
  },
  // Tabs
  tabContainer: {
    position: 'relative',
    zIndex: 10,
    marginBottom: '28px',
  },
  tabBg: {
    display: 'flex',
    padding: '4px',
    borderRadius: '14px',
    background: 'rgba(255, 255, 255, 0.04)',
    border: '1px solid rgba(255, 255, 255, 0.06)',
    backdropFilter: 'blur(10px)',
    gap: '4px',
  },
  tab: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '10px 24px',
    borderRadius: '10px',
    fontSize: '13px',
    fontWeight: 600,
    fontFamily: "'Inter', sans-serif",
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    background: 'transparent',
    color: 'rgba(255, 255, 255, 0.4)',
  },
  tabActive: {
    background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    color: '#ffffff',
    boxShadow: '0 4px 15px rgba(99, 102, 241, 0.3)',
  },
  // Card
  card: {
    position: 'relative',
    zIndex: 10,
    width: '100%',
    maxWidth: '440px',
    background: 'rgba(255, 255, 255, 0.03)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    borderRadius: '20px',
    padding: '36px',
    border: '1px solid rgba(255, 255, 255, 0.06)',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.05)',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '22px',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontSize: '13px',
    fontWeight: 600,
    color: 'rgba(255, 255, 255, 0.5)',
    letterSpacing: '0.02em',
  },
  inputWrapper: {
    display: 'flex',
    alignItems: 'center',
    background: 'rgba(255, 255, 255, 0.04)',
    borderRadius: '12px',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    overflow: 'hidden',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  inputIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '48px',
    height: '48px',
    color: 'rgba(255, 255, 255, 0.3)',
    flexShrink: 0,
  },
  input: {
    flex: 1,
    padding: '14px 16px 14px 0',
    background: 'transparent',
    border: 'none',
    outline: 'none',
    fontSize: '15px',
    color: 'rgba(255, 255, 255, 0.9)',
    fontFamily: "'Inter', sans-serif",
  },
  // Error
  errorBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 16px',
    borderRadius: '12px',
    background: 'rgba(239, 68, 68, 0.1)',
    border: '1px solid rgba(239, 68, 68, 0.2)',
    color: '#fca5a5',
    fontSize: '13px',
    fontWeight: 500,
    animation: 'slideDown 0.3s ease',
  },
  // Submit button
  submitBtn: {
    width: '100%',
    padding: '14px 24px',
    background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    color: '#ffffff',
    border: 'none',
    borderRadius: '12px',
    fontSize: '15px',
    fontWeight: 700,
    fontFamily: "'Inter', sans-serif",
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    boxShadow: '0 4px 15px rgba(99, 102, 241, 0.25)',
    marginTop: '4px',
  },
  // Footer
  footer: {
    position: 'relative',
    zIndex: 10,
    marginTop: '32px',
    fontSize: '12px',
    color: 'rgba(255, 255, 255, 0.2)',
    letterSpacing: '0.05em',
  },
};

export default styles;
